project 'EarlGreyTest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EarlGreyTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EarlGreyTest

  target 'EarlGreyTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'EarlGrey'
  end

end
